### ISSUE TITLE
Добавить возможность дешифровать старый код программы например срубеса 2022

### ISSUE THREAD

**Issue by Vovo4k** [FINVS/asciicaesar#5]
TODO

**Comment by R2U2** [comment]
не

**Comment by disco2alt** [comment]
а как насчёт сделать отдельную прогу для этого 😼

**Comment by ShakalnyKot** [comment]
ооооо ты любишь философию unix
ты любишь маленькие проги, которые делают одну вещь, но делают её хорошо

**Comment by disco2alt** [comment]
> ооооо ты любишь философию unix ты любишь маленькие проги, которые делают одну вещь, но делают её хорошо

![ac9a827cbed39e72beca77d4d9fde8c0](https://github.com/FINVS/asciicaesar/assets/131756274/787b24e3-79fc-407e-97cb-b730d57ae6d4)

**Comment by disco2alt** [comment]
Ой блять не то

**Comment by Vovo4k** [comment]
💀

**Comment by ShakalnyKot** [comment]
> > ооооо ты любишь философию unix ты любишь маленькие проги, которые делают одну вещь, но делают её хорошо
> 
> ![ac9a827cbed39e72beca77d4d9fde8c0](https://user-images.githubusercontent.com/131756274/253532033-787b24e3-79fc-407e-97cb-b730d57ae6d4.png)

![gegetgegergerge](https://github.com/FINVS/asciicaesar/assets/103893968/1dbedfc5-1151-4dda-9a7f-9fd00bed012f)

**Comment by ShakalnyKot** [comment]
ой
